### ISSUE TITLE
Modifying ABC Race to have ひらがな and カタカナ and mixed

### ISSUE THREAD

**Issue by pet3rpan** [earthiverse/altivities#23]
I am not quite sure how to customize this game myself mainly how to create a link to the copied repo on my own Github. 
The idea is to make a modified version of the abc race with hiragana and katakana for students in special education. 
It would be three modes with the basic 46 hiragana (no " or o), the 46 katakana, and a mix of the two. 

I looked at the files in the figured that I would need to have the svg files for all of the hiragana and katakana. 
This page has a list of all of the hiragana and katakana. It seems like the katakana for n is missing. 
https://studio.beatnix.co.jp/kids-it/kids-programming/scratch/scratch-material/hiragana-katakana-minchyo/

The audio files I have found from this website. 
https://www.thoughtco.com/how-to-pronounce-hiragana-japanese-hiragana-with-audio-files-4077351

All of these files are also on my repository found here. 
https://github.com/pet3rpan/media

I am not quite sure if this is the right place to make a request and it is understandable if you are busy as well. If you have the time and are willing to take a look, it would be much appreciated. Thank you.

**Comment by earthiverse** [comment]
It wouldn't take me very long to make a かなレース version.

List of things to be done:

- Gather and rename SVGs and MP3s
- Replace `lowercase` and `abcde...` with `katakana` and `アイウエオ...`,
- Replace `uppercase` with `hiragana` and `ABCDE...` with `あいうえお...`
- Make new buttons
- Make new results screen

If I make SVGs from the [UD Digi Kyokasho](https://docs.microsoft.com/en-us/typography/font-list/ud-digi-kyokasho) font, it will be in the same style, since I used the same company's font for the English letter SVGs.

**Comment by earthiverse** [comment]
https://altivities.earthiverse.ca/kanarace/

It is complete.

**Comment by pet3rpan** [comment]
Thank you very much for taking the time to work on it. It's perfect.
